// ================= 건물 데이터 (원본 데이터 전체 포함) =================
const FACILITIES_DATA = [
  { id: "0", name: "효빈대학교 정문", facility: "", floor: "", transport: "7호선 효빈대입구역", location: "서구", desc: "효빈대학교의 메인 게이트로, 트램 7호선과 바로 연결됩니다." },
  { id: "1", name: "대학본부", facility: "총무과, 시설과, 장학과, 카페", floor: "5층", transport: "2호선 효빈대역, 트램 a선 대학본부·충승당역, 모노레일 b선 대학본부·충승당역", location: "서구", desc: "대학의 행정 및 학사 운영을 총괄하는 본부 건물입니다." },
  { id: "2", name: "학생복지회관", facility: "편의점, 세탁소, 서점, 문구점, 푸드코트, 카페, 안경점, 미용실", floor: "4층", transport: "트램 a선 토목대 복지관", location: "서구", desc: "학생들을 위한 다양한 편의시설과 식당이 모여있는 복지 공간입니다." },
  { id: "3", name: "충승당", facility: "", floor: "3층", transport: "2호선 효빈대역, 트램 a선 대학본부·충승당역, 모노레일 b선 대학본부·충승당역", location: "서구", desc: "대학의 역사와 전통을 기리는 기념관이자 주요 행사가 열리는 공간입니다." },
  { id: "4", name: "학생복지타운", facility: "편의점, 우체국, 학생식당(한식뷔페), 카페", floor: "5층", transport: "2호선 효빈대역", location: "서구", desc: "우체국 등 생활 필수 시설과 넓은 학생 식당을 갖춘 복합 시설입니다." },
  { id: "5", name: "동아리관", facility: "", floor: "6층", transport: "2호선 효빈대역", location: "서구", desc: "중앙동아리방과 연습실, 공연장 등이 위치한 학생 활동의 중심입니다." },
  { id: "6-1", name: "사회과학대학 1호관", facility: "", floor: "7층", transport: "5호선 소조역, 모노레일 b선 미술사회대역", location: "북구", desc: "사회과학 계열 학과의 강의실과 연구실이 위치해 있습니다." },
  { id: "6-2", name: "사회과학대학 2호관", facility: "", floor: "7층", transport: "5호선 소조역, 모노레일 b선 사회대역", location: "북구", desc: "사회과학대학의 추가 강의 공간 및 세미나실이 있습니다." },
  { id: "6-3", name: "사회과학대학 3호관", facility: "", floor: "6층", transport: "5호선 소조역, 모노레일 b선 사회복지대역", location: "북구", desc: "특수 대학원 및 연구소가 함께 위치한 건물입니다." },
  { id: "6-4", name: "행정대학원", facility: "", floor: "5층", transport: "5호선 소조역, 모노레일 b선 사회복지대역", location: "북구", desc: "전문 행정 인력 양성을 위한 특수대학원 강의동입니다." },
  { id: "7-1", name: "사회복지학대학", facility: "카페, 편의점", floor: "6층", transport: "5호선 소조역, 모노레일 b선 사회복지대역", location: "북구", desc: "사회복지학과 강의실 및 실습실, 휴게 공간이 마련되어 있습니다." },
  { id: "7-2", name: "사회복지대학원", facility: "", floor: "5층", transport: "5호선 소조역, 모노레일 b선 미술사회대역", location: "북구", desc: "심화된 사회복지 연구와 교육이 이루어지는 대학원 건물입니다." },
  { id: "7-3", name: "종합사회복지관", facility: "", floor: "4층", transport: "5호선 소조역, 모노레일 b선 미술사회대역", location: "북구", desc: "지역 사회와 연계하여 다양한 복지 프로그램을 운영하는 실습 기관입니다." },
  { id: "8-1", name: "상과대학 1호관", facility: "", floor: "8층", transport: "모노레일 b선 법전원역", location: "북구", desc: "경영, 경제 관련 학과의 주 강의동입니다." },
  { id: "8-2", name: "상과대학 2호관", facility: "카페, 편의점", floor: "7층", transport: "모노레일 b선 법전원역", location: "서구", desc: "상과대학 학생들을 위한 편의시설과 추가 강의실이 있습니다." },
  { id: "8-3", name: "경영대학원", facility: "", floor: "6층", transport: "트램 a선 상과대·학생회관역, 모노레일 b선 상과대·학생회관역", location: "서구", desc: "MBA 과정 등 경영 전문 인력 양성을 위한 교육 공간입니다." },
  { id: "9-1", name: "인문대학 1호관", facility: "", floor: "6층", transport: "", location: "북구", desc: "인문학적 소양을 기르는 어문, 철학, 사학 계열 강의동입니다." },
  { id: "9-2", name: "인문대학 2호관", facility: "카페, 편의점", floor: "5층", transport: "", location: "북구", desc: "인문대학 교수 연구실 및 세미나실, 편의시설이 위치해 있습니다." },
  { id: "10-1", name: "언어문학대학 동양언어관", facility: "", floor: "5층", transport: "5호선 소조역", location: "북구", desc: "중어중문, 일어일문 등 동양권 언어 학과가 사용하는 건물입니다." },
  { id: "10-2", name: "언어문학대학 서양언어관", facility: "", floor: "5층", transport: "", location: "북구", desc: "영어영문, 독어독문, 불어불문 등 서양권 언어 학과가 사용하는 건물입니다." },
  { id: "11-1", name: "사범대학 본관", facility: "", floor: "7층", transport: "", location: "북구", desc: "미래 교사를 양성하는 사범대학의 행정실과 주요 강의실이 있습니다." },
  { id: "11-2", name: "사범과학관", facility: "", floor: "6층", transport: "", location: "북구", desc: "과학교육과 학생들을 위한 실험실 및 강의실이 갖춰져 있습니다." },
  { id: "11-3", name: "사범인문관", facility: "", floor: "6층", transport: "", location: "북구", desc: "국어교육, 영어교육 등 인문 계열 교육 학과 강의동입니다." },
  { id: "11-4", name: "사범사회관", facility: "", floor: "6층", transport: "", location: "북구", desc: "사회교육, 역사교육 등 사회 계열 교육 학과 강의동입니다." },
  { id: "11-5", name: "사범예체관", facility: "", floor: "5층", transport: "", location: "북구", desc: "체육교육, 미술교육, 음악교육과 실기실 및 강의실이 있습니다." },
  { id: "11-6", name: "사범기술관", facility: "", floor: "5층", transport: "", location: "북구", desc: "기술가정교육과 등의 실습 및 강의 공간입니다." },
  { id: "12", name: "생활과학대학", facility: "", floor: "6층", transport: "", location: "북구", desc: "식품영양, 의류패션 등 생활과학 분야 강의 및 실습동입니다." },
  { id: "13", name: "정루관", facility: "학생식당(패스트푸드, 양식)", floor: "3층", transport: "", location: "북구", desc: "북구 캠퍼스 학생들을 위한 식당과 휴게 라운지가 있는 건물입니다." },
  { id: "14-1", name: "기계공업대학 1호관", facility: "", floor: "8층", transport: "", location: "북구", desc: "기계공학과의 메인 강의동 및 기초 실험실이 있습니다." },
  { id: "14-2", name: "기계공업대학 2호관", facility: "", floor: "7층", transport: "", location: "서구", desc: "정밀 기계 및 로봇 공학 관련 심화 연구실이 위치해 있습니다." },
  { id: "14-3", name: "기계공업대학 3호관", facility: "", floor: "7층", transport: "", location: "서구", desc: "대형 기계 장비 실습 및 프로젝트룸이 마련되어 있습니다." },
  { id: "14-4", name: "기계공업대학 4호관", facility: "카페, 편의점", floor: "6층", transport: "", location: "북구", desc: "공과대학 학생들을 위한 편의시설과 세미나실이 있습니다." },
  { id: "14-5", name: "기계공업대학 5호관", facility: "", floor: "15층", transport: "", location: "북구", desc: "고층형 연구동으로 첨단 기계 공학 연구 센터가 입주해 있습니다." },
  { id: "15-1", name: "전기공업대학 1호관", facility: "", floor: "7층", transport: "트램 a선 화공 전기대역", location: "서구", desc: "전기전자공학부의 기초 이론 강의와 실험이 진행되는 곳입니다." },
  { id: "15-2", name: "전기공업대학 2호관", facility: "", floor: "7층", transport: "트램 a선 화공 전기대역", location: "서구", desc: "반도체 및 회로 설계 실습실이 갖춰져 있습니다." },
  { id: "15-3", name: "전기공업대학 3호관", facility: "", floor: "7층", transport: "트램 a선 화공 전기대역", location: "서구", desc: "통신 및 신호 처리 관련 연구실이 위치합니다." },
  { id: "15-4", name: "전기공업대학 4호관", facility: "", floor: "6층", transport: "트램 a선 토목대 복지관역", location: "서구", desc: "전력 시스템 및 제어 공학 관련 강의동입니다." },
  { id: "16-1", name: "토목공업대학 1호관", facility: "", floor: "6층", transport: "7호선 당선원마을역", location: "서구", desc: "토목 환경 공학과의 강의실과 구조 실험실이 있습니다." },
  { id: "16-2", name: "토목공업대학 2호관", facility: "", floor: "6층", transport: "7호선 효빈대입구역", location: "서구", desc: "지반 공학 및 수리 실험을 위한 공간입니다." },
  { id: "16-3", name: "토목공업대학 3호관", facility: "", floor: "6층", transport: "트램 a선 토목대 복지관역", location: "서구", desc: "도시 계획 및 설계 관련 실습실이 있습니다." },
  { id: "17-1", name: "화학공업대학 1호관", facility: "카페, 편의점", floor: "8층", transport: "트램 a선 화공 전기대역", location: "서구", desc: "화학공학과의 주요 강의실과 기초 화학 실험실이 있습니다." },
  { id: "17-2", name: "화학공업대학 2호관", facility: "", floor: "7층", transport: "트램 a선 화공 전기대역", location: "서구", desc: "신소재 및 고분자 공학 연구실이 위치합니다." },
  { id: "17-3", name: "화학공업대학 3호관", facility: "", floor: "7층", transport: "트램 a선 화공 전기대역", location: "서구", desc: "에너지 및 환경 화학 관련 심화 연구동입니다." },
  { id: "18", name: "체육관(실내)", facility: "", floor: "3층", transport: "7호선 효빈대입구역", location: "서구", desc: "농구, 배구, 배드민턴 등 실내 스포츠를 즐길 수 있는 체육관입니다." },
  { id: "19", name: "축구장", facility: "", floor: "야외", transport: "7호선 효빈대입구역", location: "서구", desc: "인조잔디가 깔린 국제 규격의 축구장입니다." },
  { id: "20", name: "소운동장", facility: "", floor: "야외", transport: "7호선 효빈대입구역", location: "서구", desc: "풋살 등 소규모 야외 활동을 위한 운동장입니다." },
  { id: "21", name: "대운동장", facility: "카페, 편의점", floor: "야외", transport: "2호선 효빈대역, 모노레일 b선 대운동장역", location: "서구", desc: "대형 행사와 체육 대회가 열리는 메인 운동장입니다." },
  { id: "22", name: "박물관", facility: "카페", floor: "4층", transport: "2호선 효빈대역", location: "서구", desc: "효빈대학교의 역사 자료와 유물을 전시하는 공간입니다." },
  { id: "23", name: "중앙도서관", facility: "카페, 편의점", floor: "7층", transport: "5호선 소조역, 모노레일 b선 중앙도서관역", location: "북구", desc: "방대한 장서와 최신 디지털 자료, 다양한 열람실을 갖춘 학술 정보의 중심입니다." },
  { id: "24", name: "무용대학", facility: "", floor: "5층", transport: "트램 a선/모노레일 b선 효빈대 중앙환승장역", location: "서구", desc: "무용 실기실과 공연 연습장이 갖춰진 예술 공간입니다." },
  { id: "25", name: "음악대학", facility: "", floor: "5층", transport: "모노레일 b선 중앙도서관역", location: "북구", desc: "개인 연습실, 합주실, 리사이틀홀이 있는 음악 전문 교육 시설입니다." },
  { id: "26-1", name: "예술대학 1호관", facility: "", floor: "6층", transport: "모노레일 b선 예술대역", location: "서구", desc: "디자인, 연극영화 등 예술 분야의 이론 및 실기 강의동입니다." },
  { id: "26-2", name: "예술대학 2호관", facility: "", floor: "6층", transport: "모노레일 b선 예술대역", location: "서구", desc: "조형 예술 및 미디어 아트 실습실이 위치해 있습니다." },
  { id: "27-1", name: "미술대학 1호관", facility: "", floor: "5층", transport: "모노레일 b선 미술사회대역", location: "북구", desc: "회화, 조소 등 순수 미술 분야의 실기실이 있습니다." },
  { id: "27-2", name: "미술대학 2호관", facility: "", floor: "5층", transport: "모노레일 b선 미술사회대역", location: "북구", desc: "공예, 디자인 학과의 작업실 및 전시 공간입니다." },
  { id: "27-3", name: "미술대학 3호관", facility: "", floor: "5층", transport: "모노레일 b선 미술사회대역", location: "북구", desc: "미술 대학원 및 교수 개인 작업실이 위치해 있습니다." },
  { id: "28-1", name: "자연과학대학 1호관", facility: "", floor: "7층", transport: "모노레일 b선 자연대역", location: "서구", desc: "물리, 화학, 생명과학 등 기초 과학 분야의 강의동입니다." },
  { id: "28-2", name: "자연과학대학 2호관", facility: "카페, 편의점", floor: "7층", transport: "모노레일 b선 자연대역", location: "서구", desc: "자연과학대학 학생들을 위한 실험실 및 편의시설이 있습니다." },
  { id: "28-3", name: "자연과학대학 3호관", facility: "", floor: "7층", transport: "모노레일 b선 자연대역", location: "서구", desc: "수학, 통계학 및 컴퓨터 과학 관련 강의실이 있습니다." },
  { id: "29", name: "베르데 홀", facility: "편의점", floor: "8층", transport: "2,5호선 당선역, 모노레일 b선 베르데홀역", location: "서구", desc: "국제 회의 및 대규모 행사가 가능한 컨벤션 홀과 게스트룸이 있습니다." },
  { id: "30", name: "보건진료소", facility: "", floor: "3층", transport: "모노레일 b선 보건진료소역", location: "서구", desc: "학생 및 교직원의 건강 관리를 위한 1차 진료 기관입니다." },
  { id: "31", name: "법학전문대학원", facility: "", floor: "18층", transport: "모노레일 b선 법전원역", location: "서구", desc: "법조인 양성을 위한 로스쿨 전용 건물로, 모의 법정과 법학 도서관이 있습니다." },
  { id: "32", name: "교수회관", facility: "학생교수식당", floor: "5층", transport: "모노레일 b선 법전원역", location: "서구", desc: "교직원 식당과 연회장, 세미나룸이 있는 교류 공간입니다." },
  { id: "33", name: "어린이집", facility: "", floor: "2층", transport: "트램 a선 토목대 복지관역", location: "서구", desc: "교직원 및 기혼 학생 자녀를 위한 직장 어린이집입니다." },
  { id: "34", name: "공대 부속공장", facility: "", floor: "2층", transport: "7호선 효빈대입구역", location: "서구", desc: "공과대학 학생들의 실습 및 제작을 지원하는 공장형 실습동입니다." },
  { id: "35-1", name: "교통대학 1호관", facility: "", floor: "6층", transport: "모노레일 b선 예술대역", location: "서구", desc: "교통 물류 및 철도 공학 관련 강의가 이루어지는 곳입니다." },
  { id: "35-2", name: "교통대학 2호관", facility: "", floor: "6층", transport: "모노레일 b선 예술대역", location: "서구", desc: "교통 시스템 시뮬레이션 및 관제 실습실이 있습니다." },
  { id: "35-3", name: "교통대학 3호관", facility: "", floor: "6층", transport: "모노레일 b선 예술대역", location: "북구", desc: "항공 및 해상 교통 관련 연구실이 위치해 있습니다." },
  { id: "35-4", name: "모노레일 정비센터", facility: "", floor: "1층", transport: "모노레일 b선 교통대기지역", location: "북구", desc: "교내 모노레일 차량의 점검 및 정비를 담당하는 시설입니다." },
  { id: "36", name: "방도도서관", facility: "서점", floor: "5층", transport: "모노레일 b선 교통대기지역", location: "북구", desc: "북구 캠퍼스 학생들을 위한 제2도서관입니다." },
  { id: "37", name: "학군단", facility: "", floor: "3층", transport: "", location: "서구", desc: "ROTC 후보생들의 교육 및 훈련 시설입니다." },
  { id: "38", name: "사회과학연구관", facility: "", floor: "5층", transport: "", location: "서구", desc: "사회과학 분야의 다양한 연구소들이 입주해 있는 연구 전용 건물입니다." },
  { id: "39", name: "자연과학연구관", facility: "", floor: "5층", transport: "", location: "서구", desc: "기초 과학 분야의 전문 연구실과 고가 장비실이 있습니다." },
  { id: "40", name: "보건연구소", facility: "", floor: "5층", transport: "", location: "서구", desc: "보건 및 의료 관련 융합 연구를 수행하는 연구소입니다." },
  { id: "41", name: "공학연구관", facility: "", floor: "5층", transport: "", location: "서구", desc: "공학 분야 산학 과제 및 국책 연구를 수행하는 공간입니다." },
  { id: "42", name: "교육혁신센터", facility: "문구점", floor: "4층", transport: "", location: "서구", desc: "교수 학습법 개발 및 교육 기자재를 지원하는 센터입니다." },
  { id: "43", name: "창상관", facility: "", floor: "5층", transport: "", location: "서구", desc: "학생 창업 지원 및 메이커 스페이스가 있는 창의 공간입니다." },
  { id: "44", name: "빛날관", facility: "", floor: "6층", transport: "2,5호선 당선역", location: "서구", desc: "평생교육원 및 어학원이 위치한 교육 시설입니다." },
  { id: "45", name: "전산교육관", facility: "", floor: "5층", transport: "", location: "서구", desc: "컴퓨터 실습실 및 서버실이 있는 IT 교육 허브입니다." },
  { id: "46", name: "성운관", facility: "", floor: "6층", transport: "2,5호선 당선역", location: "서구", desc: "외부 기업 입주 공간 및 산학 협력 사무실이 있습니다." },
  { id: "47-1", name: "보건대학 1호관", facility: "", floor: "6층", transport: "트램 a선 약대 보건대역", location: "서구", desc: "물리치료, 작업치료 등 보건 계열 학과 강의동입니다." },
  { id: "47-2", name: "보건대학 2호관", facility: "", floor: "6층", transport: "트램 a선 약대 보건대역", location: "서구", desc: "방사선, 임상병리 등 보건 과학 실습실이 있습니다." },
  { id: "48", name: "간호대학", facility: "편의점", floor: "6층", transport: "트램 a선 간호대-한의관역", location: "서구", desc: "간호학과 강의실 및 시뮬레이션 센터가 위치해 있습니다." },
  { id: "49", name: "의과대학", facility: "", floor: "8층", transport: "", location: "서구", desc: "의예과 및 의학과 학생들의 기초 의학 교육 공간입니다." },
  { id: "49-1", name: "한의학관", facility: "", floor: "7층", transport: "트램 a선 간호대-한의관역", location: "서구", desc: "한의과대학 강의실 및 한방 실습실이 있습니다." },
  { id: "49-2", name: "치의학관", facility: "", floor: "7층", transport: "", location: "서구", desc: "치의과대학 강의실 및 치과 기초 실습실입니다." },
  { id: "49-3", name: "수의학관", facility: "", floor: "6층", transport: "트램 a선 수의대·동물병원역", location: "서구", desc: "수의과대학 강의실 및 동물 실험실이 있습니다." },
  { id: "50", name: "약학대학", facility: "", floor: "7층", transport: "트램 a선 약대 보건대역", location: "서구", desc: "약학과 강의실 및 제약 실습실이 위치해 있습니다." },
  { id: "51", name: "기숙사A (니나관)", facility: "카페, 편의점, 세탁소", floor: "20층", transport: "2호선 효빈대역", location: "서구", desc: "최신식 아파트형 기숙사로 편의시설이 완비되어 있습니다." },
  { id: "52", name: "기숙사B (아와관)", facility: "기숙사 식당", floor: "23층", transport: "2호선 효빈대역", location: "서구", desc: "고층 기숙사로 많은 학생들을 수용하며 식당을 갖추고 있습니다." },
  { id: "53", name: "기숙사1 (희다관 등)", facility: "카페, 식당 2개", floor: "10층", transport: "", location: "서구", desc: "전통 있는 기숙사 단지로 희다관, 후등관, 성가관 등으로 구성됩니다." },
  { id: "54", name: "기숙사2 (가족동반)", facility: "편의점", floor: "12층", transport: "", location: "서구", desc: "기혼자 및 가족 동반 학생을 위한 기숙사입니다." },
  { id: "55", name: "기숙사관리동", facility: "", floor: "3층", transport: "2,5호선 당선역", location: "서구", desc: "기숙사 행정실 및 택배 보관소가 위치한 관리 건물입니다." },
  { id: "56", name: "소금하우스", facility: "게스트 하우스", floor: "5층", transport: "2,5호선 당선역", location: "서구", desc: "방문 연구자 및 외빈을 위한 숙소입니다." },
  { id: "57", name: "사대 부설고등학교", facility: "", floor: "5층", transport: "모노레일 b선 교통대기지역", location: "서구", desc: "효빈대학교 사범대학 부설 고등학교입니다." },
  { id: "58", name: "애니메이션-철도 박물관", facility: "카페, 체험관", floor: "4층", transport: "2,5호선 당선역", location: "서구", desc: "국내 유일의 애니메이션과 철도를 테마로 한 이색 박물관입니다." },
  { id: "59", name: "효빈대학교 병원 본관", facility: "카페, 편의점", floor: "15층", transport: "트램 a선 효빈대병원역", location: "서구", desc: "지역 거점 상급종합병원으로 최상의 의료 서비스를 제공합니다." },
  { id: "60", name: "치과병원", facility: "", floor: "8층", transport: "트램 a선 효빈대병원역", location: "서구", desc: "전문적인 치과 진료 및 구강 건강 관리를 담당하는 병원입니다." },
  { id: "61", name: "동물병원", facility: "", floor: "4층", transport: "트램 a선 수의대·동물병원역", location: "북구", desc: "반려동물 및 특수동물 진료를 위한 대학 부속 동물병원입니다." },
  { id: "62", name: "어린이병원", facility: "", floor: "10층", transport: "7호선 효빈성북문역", location: "서구", desc: "소아 청소년 전문 진료 센터를 갖춘 어린이 특화 병원입니다." },
  { id: "63", name: "암센터", facility: "", floor: "12층", transport: "7호선 효빈성북문역", location: "서구", desc: "암 진단 및 치료, 연구를 전문으로 하는 암 센터입니다." },
  { id: "64", name: "학술문화회관", facility: "", floor: "6층", transport: "", location: "서구", desc: "대규모 학술 대회 및 문화 공연이 열리는 회관입니다." },
];

// ================= 다국어 텍스트 데이터 =================
const TEXT_CONTENT = {
    KOR: {
        univName: "효빈대학교",
        univSub: "Hyobin National University",
        slogan: "불굴(不屈)의 역사, 혁신(革新)으로 미래를 열다",
        menu: [
            { title: "대학소개", sub: ["총장인사말", "대학이념", "대학연혁", "캠퍼스안내", "오시는길"] },
            { title: "입학안내", sub: ["수시모집", "정시모집", "편입학", "외국인전형"] },
            { title: "교육·연구", sub: ["대학(단과대)", "대학원", "학사일정", "도서관"] },
            { title: "대학생활", sub: ["장학제도", "학생복지", "동아리", "효빈뉴스"] },
            { title: "효빈광장", sub: ["공지사항", "자유게시판", "벼룩시장"] }
        ],
        utility: { login: "로그인", staff: "교직원", student: "학생", portal: "포털", library: "도서관" },
        quick: ["종합정보", "도서관", "학사일정", "교통안내", "생활관", "전화번호"],
        tabs: { notice: "공지사항", academic: "학사공지", recruit: "채용공지" },
        footer: { address: "효빈광역시 서구 대학로 1", rights: "COPYRIGHT © 2025 HYOBIN UNIV. ALL RIGHTS RESERVED." }
    },
    ENG: {
        univName: "HBNU",
        univSub: "Hyobin National University",
        slogan: "Indomitable History, Innovation Opens the Future",
        menu: [
            { title: "About", sub: ["President", "Ideology", "History", "Campus Map", "Location"] },
            { title: "Admissions", sub: ["Undergraduate", "Graduate", "Transfer", "International"] },
            { title: "Academics", sub: ["Colleges", "Grad Schools", "Calendar", "Library"] },
            { title: "Campus Life", sub: ["Scholarship", "Welfare", "Clubs", "News"] },
            { title: "Community", sub: ["Notice", "Board", "Market"] }
        ],
        utility: { login: "Login", staff: "Faculty", student: "Student", portal: "Portal", library: "Library" },
        quick: ["Portal", "Library", "Calendar", "Traffic", "Dormitory", "Directory"],
        tabs: { notice: "Notice", academic: "Academic", recruit: "Recruit" },
        footer: { address: "1, Daehak-ro, Seo-gu, Hyobin City", rights: "COPYRIGHT © 2025 HYOBIN UNIV. ALL RIGHTS RESERVED." }
    },
    CHN: {
        univName: "孝彬大学",
        univSub: "Hyobin National University",
        slogan: "不屈的历史, 创新开启未来",
        menu: [
            { title: "学校介绍", sub: ["校长致辞", "办学理念", "发展沿革", "校园导览", "来访路线"] },
            { title: "入学指南", sub: ["随时招生", "定时招生", "插班生", "留学生"] },
            { title: "教育研究", sub: ["本科", "研究生院", "校历", "图书馆"] },
            { title: "校园生活", sub: ["奖学金", "学生福利", "社团", "孝彬新闻"] },
            { title: "孝彬广场", sub: ["公告事项", "自由布告栏", "跳蚤市场"] }
        ],
        utility: { login: "登录", staff: "教职员", student: "学生", portal: "门户", library: "图书馆" },
        quick: ["综合信息", "图书馆", "校历", "交通指南", "宿舍", "电话查询"],
        tabs: { notice: "公告", academic: "教务", recruit: "招聘" },
        footer: { address: "孝彬广域市 西区 大学路 1", rights: "COPYRIGHT © 2025 HYOBIN UNIV. ALL RIGHTS RESERVED." }
    },
    JPN: {
        univName: "孝彬大学",
        univSub: "Hyobin National University",
        slogan: "不屈の歴史、革新で未来を拓く",
        menu: [
            { title: "大学紹介", sub: ["総長挨拶", "理念", "沿革", "キャンパス", "アクセス"] },
            { title: "入学案内", sub: ["随時募集", "定時募集", "編入", "外国人"] },
            { title: "教育・研究", sub: ["学部", "大学院", "学事日程", "図書館"] },
            { title: "大学生活", sub: ["奨学金", "福利厚生", "サークル", "ニュース"] },
            { title: "広場", sub: ["お知らせ", "掲示板", "フリマ"] }
        ],
        utility: { login: "ログイン", staff: "教職員", student: "学生", portal: "ポータル", library: "図書館" },
        quick: ["総合情報", "図書館", "学事日程", "交通案内", "生活館", "電話番号"],
        tabs: { notice: "お知らせ", academic: "学事", recruit: "採用" },
        footer: { address: "ヒョビン広域市 西区 大学路 1", rights: "COPYRIGHT © 2025 HYOBIN UNIV. ALL RIGHTS RESERVED." }
    },
    TAG: {
        univName: "HBNU",
        univSub: "Hyobin National University",
        slogan: "Kasaysayang Di Matitinag, Inobasyon para sa Kinabukasan",
        menu: [
            { title: "Tungkol", sub: ["Mensahe", "Ideolohiya", "Kasaysayan", "Mapa", "Lokasyon"] },
            { title: "Admissions", sub: ["Undergraduate", "Graduate", "Transfer", "International"] },
            { title: "Academics", sub: ["Kolehiyo", "Grad Schools", "Kalendaryo", "Aklatan"] },
            { title: "Buhay Kampus", sub: ["Scholarship", "Welfare", "Clubs", "Balita"] },
            { title: "Komunidad", sub: ["Abiso", "Board", "Merkado"] }
        ],
        utility: { login: "Login", staff: "Faculty", student: "Estudyante", portal: "Portal", library: "Aklatan" },
        quick: ["Portal", "Aklatan", "Kalendaryo", "Trapiko", "Dorm", "Direktoryo"],
        tabs: { notice: "Abiso", academic: "Akademiko", recruit: "Trabaho" },
        footer: { address: "1, Daehak-ro, Seo-gu, Hyobin City", rights: "COPYRIGHT © 2025 HYOBIN UNIV. ALL RIGHTS RESERVED." }
    }
};

// ================= 더미 공지사항 데이터 생성기 =================
function getNotices(lang) {
    const prefix = lang === 'KOR' ? '[공지]' : '[Notice]';
    return Array.from({ length: 15 }, (_, i) => ({
        id: i,
        title: `${prefix} ${2025} Hyobin University Notice No.${i+1}`,
        date: `2025.02.${String(28-i).padStart(2,'0')}`,
        new: i < 3
    }));
}